### ISSUE TITLE
Implement correct Rectangle identity for monoidal usage

### ISSUE THREAD

**Issue by jsbean** [dn-m/GeometryTools#53]

**Comment by mossheim** [comment]
the additive monoid unit would be all negative space (for union of bounds)
the multiplicative monoid unit would be all positive space (for intersection of bounds)

**Comment by mossheim** [comment]
i think that makes sense... intersecting two non-overlapping rectangles should give you a point at the origin of the second with a width & height of zero

**Comment by mossheim** [comment]
or actually, maybe it should return nil?

**Comment by mossheim** [comment]
`Polygon?` could also be monoidal in that way.. collision detection would just be `(a * b * c)?`

**Comment by jsbean** [comment]
Hmm, collision detection is tricky, depending on if its concave or convex. In the case that it is concave, it has to be triangulated, and composite structure needs to be compared against another collsion-detectable value.

**Comment by jsbean** [comment]
But the `additive` / `subtractive` distinction seems totally right on!

Perhaps for now we just think about `additive`?

**Comment by mossheim** [comment]
sgtm!
